# -*- coding: utf-8 -*-
"""FINALS PROJECT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1195htdHEagWtNA9PeQw2vPLG_OVPQAt3
"""

from IPython.core.alias import default_aliases
print("Welcome to our program!\nThis program solves 2 or 3 simultaenous equations at a time by means of Cramer's rule.\nTo avoid error, fractions must first be converted into decimals.")
print("\nProgram start:")
print("\nPlease type in values in the following format:")
print("If 2-unknown equation: ax + by = c\nIf 3-unknown equation: ax + by + cz = d\n")

size = int(input("How many equations to solve (2 or 3): "))

import array as arr

eq_1 = arr.array('f', [])
eq_2 = arr.array('f', [])
eq_3 = arr.array('f', [])

if size == 2:
  for i in range(1, size + 1):
    a = input("Enter a value for a" + "(" + str(i) + ")" + ": " )
    b = input("Enter a value for b" + "(" + str(i) + ")" + ": " )
    c = input("Enter a value for c" + "(" + str(i) + ")" + ": " )
    if i == 1:
      eq_1.append(float(a))
      eq_1.append(float(b))
      eq_1.append(float(c))
    else:
      eq_2.append(float(a))
      eq_2.append(float(b))
      eq_2.append(float(c))
  print("\nCalculating...")

elif size == 3:
  for i in range(1, size + 1):
    a = input("Enter a value for a" + "(" + str(i) + ")" + ": " )
    b = input("Enter a value for b" + "(" + str(i) + ")" + ": " )
    c = input("Enter a value for c" + "(" + str(i) + ")" + ": " )
    d = input("Enter a value for d" + "(" + str(i) + ")" + ": " )
    if i == 1:
      eq_1.append(float(a))
      eq_1.append(float(b))
      eq_1.append(float(c))
      eq_1.append(float(d))
    if i == 2:
      eq_2.append(float(a))
      eq_2.append(float(b))
      eq_2.append(float(c))
      eq_2.append(float(d))
    if i == 3:
      eq_3.append(float(a))
      eq_3.append(float(b))
      eq_3.append(float(c))
      eq_3.append(float(d))
  print("\nCalculating...")

else:
  print("\nSorry, but I can't answer that...")

def soln2():
  det_k = (eq_1[0] * eq_2[1]) - (eq_1[1] * eq_2[0])
  det_a = (eq_1[2] * eq_2[1]) - (eq_1[1] * eq_2[2])
  det_b = (eq_1[0] * eq_2[2]) - (eq_1[2] * eq_2[0])
  if (eq_1[0] / eq_2[0]) == (eq_1[1] / eq_2[1]) == (eq_1[2] / eq_2[2]):
    print("\nYour system of equations has infintely many solutions!")
  elif det_k == 0:
    print("\nYour system of equations has no real solutions...")
  else:
    a = det_a / det_k
    b = det_b / det_k
    print("\nYour solutions are:", "\nx: ", a, "\ny: ", b)

def soln3():
  det_k = ((eq_1[0] * eq_2[1] * eq_3[2]) + (eq_1[1] * eq_2[2] * eq_3[0]) + (eq_1[2] * eq_2[0] * eq_3[1])) - ((eq_1[2] * eq_2[1] * eq_3[0]) + (eq_1[1] * eq_2[0] * eq_3[2]) + (eq_1[0] * eq_2[2] * eq_3[1]))
  det_a = ((eq_1[3] * eq_2[1] * eq_3[2]) + (eq_1[1] * eq_2[2] * eq_3[3]) + (eq_1[2] * eq_2[3] * eq_3[1])) - ((eq_1[2] * eq_2[1] * eq_3[3]) + (eq_1[1] * eq_2[3] * eq_3[2]) + (eq_1[3] * eq_2[2] * eq_3[1]))
  det_b = ((eq_1[0] * eq_2[3] * eq_3[2]) + (eq_1[3] * eq_2[2] * eq_3[0]) + (eq_1[2] * eq_2[0] * eq_3[3])) - ((eq_1[2] * eq_2[3] * eq_3[0]) + (eq_1[3] * eq_2[0] * eq_3[2]) + (eq_1[0] * eq_2[2] * eq_3[3]))
  det_c = ((eq_1[0] * eq_2[1] * eq_3[3]) + (eq_1[1] * eq_2[3] * eq_3[0]) + (eq_1[3] * eq_2[0] * eq_3[1])) - ((eq_1[3] * eq_2[1] * eq_3[0]) + (eq_1[1] * eq_2[0] * eq_3[3]) + (eq_1[0] * eq_2[3] * eq_3[1]))
  if det_k == 0 and (det_a == 0 or det_b == 0 or det_c == 0):
    print("\nYour system of equations has infintely many solutions!")
  elif det_k == 0:
    print("\nYour system of equations has no real solutions...")
  else:
    a = det_a / det_k
    b = det_b / det_k
    c = det_c / det_k
    print("\nYour solutions are:", "\nx: ", a, "\ny: ", b, "\nz: ", c)

if size == 2:
  soln2()
if size == 3:
  soln3()